HSPC-174: updated java to version 24
hyperskill/epicbox-images pull request #132
Opened 2024-09-10 18:40 UTC by polischuks

**YouTrack Issues**:
[#HSPC-174](https://vyahhi.myjetbrains.com/youtrack/issue/HSPC-174)

**Description**

2024-09-11 17:37 UTC, meanmail commented
1. Add build to CI
2. Delete Java 17, use single Dockerfile for Java

2024-09-11 17:38 UTC, meanmail requested changes
1. Add build to CI
2. Delete Java 17, use single Dockerfile for Java

2024-09-12 07:42 UTC, polischuks commented
@meanmail
> 1. Add build to CI
> 2. Delete Java 17, use single Dockerfile for Java

done.

2024-09-12 08:09 UTC, meanmail approved these changes

2024-09-12 08:26 UTC, merged